export const projects = [
  {
    slug: 'ticker-svg',
    name: 'Ticker SVG',
    description: 'Stock ticker SVG generator',
    service: 'ticker-svg.service',
    port: 3002,
    path: '/home/ubuntu/ticker-svg',
    url: 'https://server.jedbillyb.com/banner',
  },
  {
    slug: 'gateway',
    name: 'API Gateway',
    description: 'Node.js API gateway and reverse proxy',
    service: 'gateway.service',
    port: 8080,
    path: '/home/ubuntu/gateway',
  },
  {
    slug: 'ghook',
    name: 'GitHub Discord Bot',
    description: 'GitHub webhook to Discord notification bot',
    service: 'ghook.service',
    port: 3000,
    path: '/home/ubuntu/ghook',
  },
  {
    slug: 'mission-control',
    name: 'Mission Control',
    description: 'Telegram server monitoring and alert bot',
    service: 'mission-control-alerts.service',
    path: '/home/ubuntu/mission-control',
  },
  {
    slug: 'mission-control-web',
    name: 'Mission Control Web',
    description: 'Mission Control web dashboard',
    service: 'mission-control-web.service',
    port: 4000,
    path: '/home/ubuntu/mission-control',
    url: 'https://status.jedbillyb.com',
  },
  {
    slug: 'profile-server',
    name: 'Profile Server',
    description: 'Personal profile and project server',
    service: 'profile-server.service',
    port: 3003,
    path: '/home/ubuntu/profile-server',
    url: 'https://server.jedbillyb.com/setup',
  },
  {
    slug: 'vehicle-api',
    name: 'NZ Vehicle Finder API',
    description: 'NZ motor vehicle register search API',
    pm2: 'vehicle-api',
    port: 3001,
    path: '/home/ubuntu/nz-vehicle-finder',
    url: 'https://vehiclefinder.co.nz',
  },
  {
    slug: 'manifest-dashboard',
    name: 'Server Manifest Dashboard',
    description: 'TanStack Start SSR server dashboard',
    pm2: 'manifest-dashboard',
    path: '/home/ubuntu/server-manifest-react',
    url: 'https://server.jedbillyb.com/setup',
  },
  {
    slug: 'discord-vc-bot',
    name: 'Discord VC Bot',
    description: 'Discord voice channel notification bot',
    pm2: 'discord-vc-bot',
    path: '/home/ubuntu/discord-vc-bot',
  },
  {
    slug: 'posthog-webhook',
    name: 'PostHog Webhook',
    description: 'Forwards PostHog analytics events to Telegram',
    service: 'posthog-webhook.service',
    port: 8000,
    path: '/home/ubuntu/posthog-notify',
  },
  {
    slug: 'openclaw',
    name: 'Openclaw',
    description: 'Personal AI agent with Telegram and Discord integration',
    port: 18789,
    path: '/home/ubuntu/openclaw',
  },
  {
    slug: 'server-api',
    name: 'Server API',
    description: 'server.jedbillyb.com REST API server',
    service: 'server-api.service',
    port: 4001,
    path: '/home/ubuntu/server-api',
    url: 'https://server.jedbillyb.com/api/status',
  },
];
