name: Deploy

on:
  push:
    branches: [v1]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://server.jedbillyb.com
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ubuntu
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /home/ubuntu/server.jedbillyb.com
            git fetch origin v1
            git reset --hard origin/v1
